######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 24 18:07:08 2010
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

CONFIG += staticlib

# Input
HEADERS += src/CSVBuilder.hpp
SOURCES += src/CSVBuilder.cpp
