######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 24 17:52:17 2010
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../src
INCLUDEPATH += . ../src

# Input
HEADERS += testCSVBuilder.hpp CSVBuilder.hpp
SOURCES += testCSVBuilder.cpp CSVBuilder.cpp
